src/components/sections/FeaturesSection/FeatureCard/FeatureCard.tsx
src/components/sections/FeaturesSection/FeatureCard/index.ts
src/components/sections/FeaturesSection/FeatureCard/styles.ts
src/components/sections/FeaturesSection/FeaturesList/FeaturesList.tsx
src/components/sections/FeaturesSection/FeaturesList/index.ts
src/components/sections/FeaturesSection/FeaturesList/styles.ts
src/components/sections/FeaturesSection/FeaturesSection.tsx
src/components/sections/SectionRenderer/SectionRenderer.tsx

Added Homepage Features section
**PR Checklist**
**Screenshots/Video after change**
Add screenshots with the changes applied here.

Homepage features section

---

src/components/sections/HeroSection/HeroSection.tsx
src/components/sections/InnerSection/InnerSection.tsx
src/components/sections/InnerSection/index.ts
src/components/sections/InnerSection/styles.ts
src/components/sections/RichTextSection/RichTextSection.tsx
src/components/sections/SplitSection/SplitSection.tsx
src/components/sections/SplitSection/styles.ts
src/types/components/sections/index.ts

Added split section
**PR Checklist**
**Screenshots/Video after change**

Homepage split section

---

src/components/sections/NewsletterSection/NewsletterSection.tsx
src/components/sections/SectionRenderer/SectionRenderer.tsx
src/pages/contacts/index.tsx

added newsletter section to contacts page

---

src/pages/benefits/index.tsx

Added newsletter sectiont to the benefits page

Benefits page

---

src/components/pages/contacts/contactsCards/ContactsCards.tsx
src/components/pages/contacts/contactsCards/index.ts
src/components/pages/contacts/contactsCards/styles.ts
src/components/pages/slugPageBreadcrumbs/SlugPageBreadcrumbs.tsx
src/components/pages/slugPageBreadcrumbs/index.ts
src/components/sections/ContactsSection/ContactsSection.tsx
src/components/sections/RichTextSection/RichTextSection.tsx
src/components/sections/RichTextSection/styles.ts
src/components/sections/SectionRenderer/SectionRenderer.tsx
src/pages/[slug].tsx
src/pages/contacts/index.tsx
src/pages/contacts/style.ts
src/types/components/sections/index.ts

Description
Added RETURNS, COMPLAINTS AND EXCHANGE page
Type of change
PR Checklist
Screenshots/Video after change

added returns page

---

src/components/sections/RichTextSection/RichTextSection.tsx
src/components/sections/RichTextSection/styles.ts
src/pages/[slug].tsx
src/styles/components.ts
src/types/components/sections/index.ts

Added content and styling for Public Offer Page
**PR Checklist**
**Screenshots/Video after change**

added public offer page

---

.eslintignore
.eslintrc.json
.prettierignore
.prettierrc
package-lock.json
package.json

1. Add Prettier Extensions 
2. Add ESLint Extensions 
3. git pull origin dev + npm i
4. .prettierrc имеет конфигурацию:
{
"semi": true,
"singleQuote": true,
"trailingComma": "es5",
"bracketSpacing": true,
"jsxBracketSameLine": false,
"printWidth": 80,
"tabWidth": 2,
"arrowParens": "avoid",
"endOfLine": "lf"
}
- semi: Добавляет точку с запятой в конце каждой строки.
- singleQuote: Использует одинарные кавычки вместо двойных.
- trailingComma: Добавляет запятую в конце последнего элемента в объектах и массивах, где это допустимо в ES5 (например, в массивах и объектах, но не в функциях).
- bracketSpacing: Добавляет пробелы внутри фигурных скобок.
- jsxBracketSameLine: Переносит закрывающую скобку JSX на новую строку.
- printWidth: Устанавливает максимальную длину строки. Если строка превышает …

added configuration

---

src/components/shop/categories/CategoriesMenu/styles.ts

Corrects a warning related to CategoriesMenu - shouldForwardProp was used. 

fix warning CategoriesMenu 

---

src/components/global/buttons/FavoriteButton/FavoriteButton.tsx
src/components/shop/ProductCardsList/ProductCardList.tsx
src/components/shop/product/ProductCard/ProductCard.tsx
src/components/shop/product/ProductCard/styles.ts
src/hooks/useGetAuthToken.ts
src/pages/my-account/login/index.tsx
src/utils/auth/userLocalStorage.ts

WishList проверить продукт лист на получение userdata.
- Когда кликаешь по favorite button на продукте WishList то все сердечки isLoading, можно переделать как на Еве, что при наведении появляетя сердечки и только оно  меняет статус.
- Терялся token при нажатии на favorite button.

Wish list bugfix

---

src/components/global/popups/MiniCart/MiniCart.tsx
src/components/pages/account/AccountLayout/styles.ts
src/components/pages/account/WishListTable/WishListTable.tsx
src/components/pages/cart/CartQuantity/CartQuantity.tsx
src/components/pages/cart/CartTable/CartTable.tsx
src/components/pages/product/ProductInfo/ProductInfo.tsx
src/components/shop/product/ProductCard/ProductCard.tsx
src/hooks/useWishlist.ts
src/pages/cart/index.tsx
src/styles/components.ts
src/types/pages/cart/index.ts
src/utils/cart/checkProductAvailability.ts

Fix minicart, links in wishlist, cart loading, and the logic for adding to basket from wishlist.

fix variation products

---

src/components/shop/Archive/Archive.tsx
src/components/shop/Archive/styles.ts
src/components/shop/ProductCardsList/ProductCardList.tsx
src/components/shop/ProductCardsList/styles.ts
src/translations/de.json
src/translations/en.json
src/translations/pl.json
src/translations/ru.json
src/translations/uk.json
src/types/components/shop/productsList/index.ts

PLT 008, 011 Catalog

---

src/components/shop/Archive/Archive.tsx
src/components/shop/filtration/FilterPanel/FilterPanel.tsx
src/components/shop/filtration/PriceFilter/PriceFilter.tsx
src/hooks/useCurrencyConverter.ts
src/types/components/shop/filters/index.ts

There may be bugs, the task is in progress.

in process

---

src/store/store.ts

Description
I commented out the saving of the cartItems in localStorage through middleware, and everything seems to be working fine.
Type of change
Feature (add cartSlice to localStorage with Redux-persist)
---
- https://app.asana.com/0/0/1209193121283038

add save cartslice to localstorage with redux-persist

---

src/components/global/reviews/Reviews/Reviews.tsx
src/components/sections/ReviewsSection/ReviewsCard/ReviewsCard.tsx
src/components/sections/ReviewsSection/ReviewsSlider/ReviewsSlider.tsx
src/store/rtk-queries/wooCustomApi.ts
src/types/services/wooCustomApi/customer/index.ts

Ensure that the reviews block displays only the reviews for the specific product.
---
- https://app.asana.com/0/0/1209291554644765

add correct reviews to product page

---

src/components/global/reviews/Reviews/Reviews.tsx
src/components/sections/ReviewsSection/ReviewsCard/ReviewsCard.tsx
src/components/sections/ReviewsSection/ReviewsSlider/ReviewsSlider.tsx
src/components/widgets/BottomMenu/BottomMenu.tsx
src/components/widgets/Header/Header.tsx
src/store/rtk-queries/wooCustomApi.ts
src/types/services/wooCustomApi/customer/index.ts

Fixes the incorrect wishlist product count display in the Header and BottomMenu. Now, the count updates correctly based on the user's wishlist.
---
- https://app.asana.com/0/0/1209226361783521

Fix wishlist length

---

src/components/global/icons/DeliveryIcon/DeliveryIcon.tsx
src/components/global/icons/DeliveryIcon/index.ts
src/components/pages/product/DeliveryTimer/DeliveryTimer.tsx
src/components/pages/product/DeliveryTimer/index.ts
src/components/pages/product/DeliveryTimer/styles.ts
src/components/pages/product/ProductInfo/ProductInfo.tsx
src/translations/de.json
src/translations/en.json
src/translations/pl.json
src/translations/ru.json
src/translations/uk.json
src/utils/isWeekdayBeforeTwoPM.ts

Add a notification on the product page for same-day shipping if the order is placed before 14:00.

add timer for today delivery to product page

---

src/components/shop/filtration/ColorsFilter/ColorsFilter.tsx
src/components/shop/filtration/ColorsFilter/styles.ts
src/components/shop/filtration/FilterPanel/FilterPanel.tsx
src/components/shop/filtration/PriceFilter/PriceFilter.tsx
src/components/shop/filtration/PriceFilter/styles.ts
src/components/shop/filtration/filterActionButtons/FilterActionButtons.tsx
src/components/shop/filtration/filterActionButtons/styles.ts
src/components/shop/filtration/priceFilterSkeleton/PriceFilterSkeleton.tsx
src/components/shop/product/ProductCard/ProductCard.tsx

Catalog filters

---

src/components/global/forms/AmbassadorFrom/AmbassadorFrom.tsx
src/types/components/global/forms/common/index.ts

fix phone validation
fix preview for pdf and gif
---
- https://app.asana.com/0/0/1209396761779586

fix phone validation ambassador form

---

src/components/sections/RichTextSection/RichTextSection.tsx
src/components/sections/RichTextSection/styles.ts

---
- https://app.asana.com/0/0/1209365334488872

add parser for richtext

---

src/components/pages/product/DeliveryTimer/DeliveryTimer.tsx
src/translations/de.json
src/translations/en.json
src/translations/pl.json
src/translations/ru.json
src/translations/uk.json

Add a message saying "The order will be shipped on the next business day" after 14:00 on working days and on weekends.
---
- https://app.asana.com/0/0/1209421801033428

add message delivery next business day

---

src/components/global/reviews/Reviews/Reviews.tsx
src/store/rtk-queries/wooCustomApi.ts
src/types/services/wooCustomApi/customer/index.ts

---
- https://app.asana.com/0/0/1209421801033449

newest product comments

---

src/components/global/SearchBar/SearchBar.tsx
src/pages/blog/[slug].tsx

Fixed an issue where the search bar remained open after selecting a variant. Now, the search bar clears automatically once an option is chosen.
---
- https://app.asana.com/0/0/1209160134136799

clear and close searchbar after choose variant

---

src/components/global/accordions/CustomSortAccordion/CustomSortAccordion.tsx
src/components/global/accordions/CustomSortAccordion/styles.ts
src/components/global/buttons/AddToBasketButton/styles.ts
src/components/shop/Archive/Archive.tsx
src/components/shop/product/ProductCard/styles.ts
src/pages/blog/[slug].tsx
src/utils/getPluralForm.ts

Added a function to correctly display the word "products" based on product count for supported languages.
Fixed bug on the Search Results page.
Linked task: https://app.asana.com/0/1207865979189211/1209068587968678

fixed bug search results

---

src/components/pages/product/ProductInfo/ProductInfo.tsx
src/components/pages/product/ProductOptionsPanel/ProductOptionsPanel.tsx
src/types/pages/product/productOptionsPanel/index.ts
src/utils/getSaleVariation.ts

Automatically selects a sale variation of a product if available. The sale variation is set as the default when its price is marked as a sale.

first show sale variation

---

src/components/global/SearchResultsComponent/SearchResultsComponent.tsx
src/components/global/popups/MiniCart/MiniCart.tsx
src/components/pages/account/AccountInfoBlockList/AccountInfoBlockList.tsx
src/components/pages/account/WishListTable/WishListTable.tsx
src/components/pages/cart/CartTable/CartTable.tsx
src/components/pages/cart/OrderBar/OrderBar.tsx
src/components/pages/cart/OrderSummary/OrderSummary.tsx
src/components/pages/order/OrderTable/OrderTable.tsx
src/components/pages/product/ProductInfo/ProductInfo.tsx
src/components/pages/product/ProductPrice/ProductPrice.tsx
src/components/shop/ProductCardsList/ProductCardList.tsx
src/components/shop/product/ProductCard/ProductCard.tsx
src/hooks/useCurrencyConverter.ts
src/pages/product/[slug].tsx
src/types/components/shop/product/productCard/index.ts
src/utils/price/formatPrice.ts

Added a new feature for formatting prices with koma and currency symbols and includes a code refactor by introducing a custom hook.
---
- https://app.asana.com/0/0/1209443045140650

Format price

---

src/components/pages/account/AccountInfoBlock/styles.ts
src/pages/my-account/index.tsx

Fixed bugs in account layout
---
- https://app.asana.com/0/0/1209567559229752
- https://app.asana.com/0/0/1209567559229799
- https://app.asana.com/0/0/1209567559229722

fixed icon and order block in account layout

---

emotion.d.ts
src/components/global/popups/HamburgerMenu/HamburgerMenu.tsx
src/components/global/sliders/VerticalSliderMenu/VerticalSliderMenu.tsx
src/components/menus/MenuSkeleton/MenuSkeleton.tsx
src/components/menus/MenuSkeleton/styles.ts
src/components/menus/Nav/Nav.tsx
src/components/shop/categories/CategoriesMenu/CategoriesMenu.tsx
src/components/widgets/Footer/Footer.tsx
src/components/widgets/Header/Header.tsx
src/components/widgets/TopBar/TopBar.tsx
src/pages/blog/index.tsx
src/styles/theme.ts
src/types/menus/Skeletons/index.ts
src/types/pages/blog/index.ts
src/utils/zodValidators/validateWpBlogPage.ts

---
- https://app.asana.com/0/0/1209595627900556

Nav skeletons style

---

src/components/widgets/Header/Header.tsx

Hide the search bar when selecting an option, clicking the search icon, pressing Enter, or clicking "Show All."
---
- https://app.asana.com/0/0/1209068587968678

hide searchbar when click, enter, choose an option or show all

---

src/components/pages/benefits/BenefitsAccordion/BenefitsAccordion.tsx
src/translations/de.json
src/translations/en.json
src/translations/pl.json
src/translations/ru.json
src/translations/uk.json

---
- https://app.asana.com/0/0/1209232947869722

add translate subtitle loyalty page

---

next.config.mjs
src/components/sections/InnerSection/styles.ts
src/components/sections/RichTextSection/RichTextSection.tsx
src/components/sections/RichTextSection/styles.ts
src/styles/components.ts

https://app.asana.com/0/1208606443803617/1209627289112270/f
https://app.asana.com/0/1208606443803617/1209627289112260/f
https://app.asana.com/0/1208606443803617/1209627289112246/f
https://app.asana.com/0/1208606443803617/1209627289112234/f
https://app.asana.com/0/1208606443803617/1209627289112212/f
https://app.asana.com/0/1208606443803617/1209627289112198/f

fix processing wp content

---

src/components/global/forms/LoginForm/LoginForm.tsx
src/components/global/forms/RegistrationForm/RegistrationForm.tsx
src/components/global/forms/ShippingForm/ShippingForm.tsx
src/hooks/useRegisterUser.ts
src/pages/api/wp/[...path].ts
src/services/wpRestApi.ts
src/store/rtk-queries/wpApi.ts
src/translations/de.json
src/translations/en.json
src/translations/pl.json
src/translations/ru.json
src/translations/uk.json
src/types/components/global/forms/LoginForm/index.ts
src/types/services/wpRestApi/auth/index.ts
src/utils/auth/setAuthCookie.ts
src/utils/checkUserTokenInServerSide.ts

>**If we create such logic, we need to specify how long the token should live in two different cases? Now it is stored in cookies for 7 days, but I don't know how on the server. We can say that remember me mode is enabled by default.**
---
- https://app.asana.com/0/0/1209627289112079

remember me checkbox loginform

---

src/pages/cart/index.tsx
src/pages/my-account/orders/index.tsx
src/pages/my-account/wishlist/index.tsx

fixed request params

---

src/components/global/forms/AmbassadorFrom/AmbassadorFrom.tsx
src/components/global/forms/AmbassadorFrom/styles.ts
src/components/global/forms/CustomFormInput/CustomFormInput.tsx
src/components/global/forms/CustomFormInput/styles.ts
src/components/pages/contacts/ContactsForm/ContactsForm.tsx
src/styles/components.ts
src/types/components/global/forms/customFormInput/index.ts

fix country select, gap, textarea, fileupload input height
https://app.asana.com/0/1208606443803617/1209799400555562/f

fix ambassador design

---

src/components/global/buttons/NotifyBasketButton/NotifyBasketButton.tsx
src/components/global/buttons/NotifyBasketButton/index.ts
src/components/global/buttons/NotifyBasketButton/styles.ts
src/components/global/forms/NotifyPopupForm/NotifyPopupForm.tsx
src/components/pages/account/WishListTable/WishListTable.tsx
src/components/pages/product/ProductInfo/ProductInfo.tsx
src/components/sections/RichTextSection/styles.ts
src/components/shop/product/ProductCard/ProductCard.tsx
src/hooks/useWishlist.ts
src/pages/my-account/wishlist/index.tsx
src/types/store/rtk-queries/instockNotifier.ts

---
- https://app.asana.com/0/0/1209825844879653
- https://app.asana.com/0/0/1209857294502928

Feat notify button

---

src/components/global/Rating/Rating.tsx
src/components/global/forms/CustomTextArea/CustomTextArea.tsx
src/components/global/forms/CustomTextArea/index.ts
src/components/global/forms/CustomTextArea/styles.ts
src/components/global/forms/CustomTextField/CustomTextField.tsx
src/components/global/forms/CustomTextField/styles.ts
src/components/global/forms/NotifyPopupForm copy/NotifyPopupForm.tsx
src/components/global/icons/StarIcon/StarIcon.tsx
src/components/global/popups/CommentPopup/CommentPopup.tsx
src/components/global/popups/CommentPopup/styles.ts
src/components/global/popups/NotifyPopup/NotifyPopup.tsx
src/components/global/popups/NotifyPopup/style.ts
src/components/global/popups/PopupContainer/PopupContainer.tsx
src/components/global/reviews/Reviews/Reviews.tsx
src/components/pages/product/ProductInfo/ProductInfo.tsx
src/components/sections/ReviewsSection/ReviewsCard/styles.ts
src/components/sections/ReviewsSection/ReviewsSlider/ReviewsSlider.tsx
src/translations/de.json
src/translations/en.json
src/translations/pl.json
src/translations/ru.json
src/translations/uk.json
src/types/components/global/rating/index.ts
src/utils/getValidationSchema.ts

https://app.asana.com/0/1205365401411204/1209825844879672

Feat commemts for all

---

src/components/global/buttons/WhatsAppButton/WhatsAppButton.tsx
src/components/global/buttons/WhatsAppButton/styles.ts

style: changed button background color

---

src/components/global/popups/InfoPopup/InfoPopup.tsx
src/components/global/popups/InfoPopup/style.ts
src/components/menus/Nav/Nav.tsx
src/store/slices/themeOptionsSlice.ts
src/types/services/wpCustomApi/menus/index.ts
src/types/services/wpCustomApi/themeOptions/index.ts

https://app.asana.com/0/1205365401411204/1209825844879642

added sizes, styles, types

---

src/pages/my-account/index.tsx
src/pages/my-account/orders/index.tsx

everything expect 'trash' and 'onHold'
https://app.asana.com/0/1208606443803617/1209567559229704/f

added a filter for orders

---

src/pages/cart/index.tsx
src/pages/checkout/index.tsx
src/pages/my-account/index.tsx
src/pages/my-account/loyalty/index.tsx
src/types/services/userTotals/index.ts
src/utils/consts.ts
src/utils/getLoyaltyLevel.ts

Replaced frontend loyalty status calculation with backend-provided data.
---
- https://app.asana.com/0/0/1209909296857409

change loyalty status login from back

---

src/components/global/popups/InfoPopup/InfoPopup.tsx
src/components/global/popups/InfoPopup/style.ts

fix: removed paddings, changed close icon

---

src/pages/my-account/orders/[slug].tsx

---
- https://app.asana.com/0/0/1209945534594806
- https://app.asana.com/0/0/1209796858972553

Feat view orders

---

src/components/Layout/Layout.tsx
src/components/global/SearchInputComponent/SearchInputComponent.tsx
src/components/global/SearchResultsComponent/SearchResultsComponent.tsx
src/components/pages/account/WishListTable/WishListTable.tsx
src/components/shop/Archive/Archive.tsx
src/components/shop/product/ProductCard/ProductCard.tsx
src/hooks/useLanguageSwitcher.ts
src/hooks/useSearchLogic.tsx
src/pages/checkout/index.tsx
src/pages/product-category/[...slugs].ts
src/pages/search/[...slugs].ts
src/services/transformers/transformCategoriesIntoLinks.ts
src/services/transformers/transformSubcategoriesIntoLinks.ts
src/store/listeners/cartSliceListener.ts
src/store/slices/languageSlice.ts
src/types/components/shop/archive/index.ts

---
- https://app.asana.com/0/0/1209945534594793

Fix default language

---

src/components/pages/404/ErrorPage.tsx
src/components/pages/404/styles.ts
src/pages/404.tsx
src/pages/500.tsx

---
- https://app.asana.com/0/0/1209986706355613

fix: removed gsp

---

src/components/global/popups/CommentPopup/styles.ts
src/components/pages/product/ProductOptionsPanel/ProductOptionsPanel.tsx
src/components/pages/product/ProductSwiper/ProductSwiper.tsx
src/types/components/shop/product/products.ts
src/utils/filterFirstAttributeOptions.ts

Added filtering for the first attribute: it now displays only those options that are valid in combination with all other attributes.
Implemented automatic validation and update of subsequent attribute options when the first attribute changes — if any selected options become invalid (i.e., do not exist in any variation), they are reset to valid defaults.
Updated styles for the product review popup for better visual consistency.
---
- https://app.asana.com/0/0/1209998994002264

Filter attributes

---

src/components/pages/product/ProductInfo/ProductInfo.tsx
src/components/pages/product/ProductSwiper/ProductSwiper.tsx
src/components/shop/categories/CategoriesMenu/CategoriesMenu.tsx
src/components/shop/categories/CategoriesMenu/styles.ts
src/types/components/shop/product/products.ts

Show image for variation if exist
---
- https://app.asana.com/0/0/1210079362831200

Variation image

---

src/pages/_document.tsx

---
- https://app.asana.com/0/0/1210121101475255

add google analytics script to _document.tsx

---

src/components/pages/pageTitle/PageTitle.tsx
src/pages/product/[slug].tsx
src/types/components/shop/product/productSEO/index.ts
src/types/components/shop/product/products.ts

This PR adds SEO for the product page. It introduces a seo_data field containing metadata for SEO, such as title, description, images. It also adds types for SEO information for the product type.
---
- https://app.asana.com/0/0/1210171447529822

Seo product

---

src/components/pages/cart/CartTable/CartTable.tsx
src/utils/cart/checkProductAvailability.ts

---
- https://app.asana.com/0/0/1210078462925432

fixed mobile cart deleting product warning bug

---

src/pages/blog/index.tsx
src/store/rtk-queries/wpCustomApi.ts
src/types/pages/blog/index.ts

---
- https://app.asana.com/0/0/1210248354532641

added seo for post category

---

src/pages/product/[slug].tsx
src/types/components/shop/product/products.ts

---
- https://app.asana.com/0/0/1210207027602597

added upsells/crossells product

---

src/pages/checkout/index.tsx
src/utils/checkout/getCalculatedMethodCostByWeight.ts

This reverts commit 853f3e8c25fcd0795ec0bb4cb62e082df3ef6db2.

Revert "Revert "added coast rule to calculating free shipping""

---

src/pages/index.tsx

https://app.asana.com/1/1199554203587884/project/1205365401411204/task/1210270282107000

added structuredData to the Home page

---

src/components/pages/blog/blogTitle/BlogTitle.tsx
src/components/shop/Archive/Archive.tsx
src/pages/[slug].tsx
src/pages/blog/[slug].tsx
src/pages/blog/index.tsx
src/pages/index.tsx
src/pages/product/[slug].tsx
src/styles/components.ts
src/types/services/wpCustomApi/index.ts

---
- https://app.asana.com/0/0/1210424937106223

Fix add seo data

---

src/components/global/forms/BillingForm/BillingForm.tsx
src/components/global/forms/BillingForm/style.ts
src/translations/de.json
src/translations/en.json
src/translations/pl.json
src/translations/ru.json
src/translations/uk.json

---
- https://app.asana.com/0/0/1210409345114729

added note
